### ISSUE TITLE
Diplaying ERROR while using this template in visual studio 2017 15.6 with angualar 5 and asp.net core 2.1

### ISSUE THREAD

**Issue by Ramasagar** [creativetimofficial/material-dashboard-angular2#33]
Displaying following error

An unhandled exception occurred while processing the request.
WinHttpException: The server returned an invalid or unrecognized response
System.Threading.Tasks.RendezvousAwaitable<TResult>.GetResult()
HttpRequestException: An error occurred while sending the request.
System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
HttpRequestException: Failed to proxy the request to http://localhost:62681/, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:62681/.

The underlying exception message was 'An error occurred while sending the request.'.Check the InnerException for more details.
Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task<Uri> baseUriTask, CancellationToken applicationStoppingToken, bool proxy404s)

**Comment by chelaruc** [comment]
Hi @Ramasagar,

Sorry for the late response. Can you tell me if that's an issue with our product or it's a back-end issue?

All the best,
Ciprian
