### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by burgosambf** [creativetimofficial/material-dashboard-angular2#37]
I can't display a select list beacuse doesn't find the mat-select component, how can I do it?

`<mat-select placeholder="Seleccione un plan" id="plan" name="codPlan" [(ngModel)]="loteIndividual.codePlan" class="form-control">
                                                                                                        <mat-option *ngFor="let c of planes" [value]="c.code">{{c.description}}</mat-option>
                                                                                                    </mat-select>`

**Comment by chelaruc** [comment]
@burgosambf have you imported the MatSelect module?

**Comment by burgosambf** [comment]
Yes I have, the MatSelectModule and the MatOptionModule but the problem still remains, it seems that doesn't reconize it

**Comment by chelaruc** [comment]
@burgosambf I think you need to move those modules to a higher one(ex: AppModule)
