### ISSUE TITLE
No Login Page etc, no dropdowns

### ISSUE THREAD

**Issue by foxenn** [creativetimofficial/material-dashboard-angular2#40]
Hey, there are no No Login Page etc, no dropdowns etc, apart from these all are great.

**Comment by chelaruc** [comment]
@foxenn you have dropdown on the navbar and the login page is a feature in PRO version [https://www.creative-tim.com/product/material-dashboard-pro-angular2](https://www.creative-tim.com/product/material-dashboard-pro-angular2). Best, Ciprian
