### ISSUE TITLE
Problem on changing color

### ISSUE THREAD

**Issue by Xipotera** [creativetimofficial/material-dashboard-angular2#41]
Hi,
actually i try the free version before buy the pro. 
When i change the color in _brand.scss the header of form do not change, is it a limitation of the free version?

![capture d ecran 2018-07-11 a 11 22 46](https://user-images.githubusercontent.com/15159850/42562939-483426b4-84fd-11e8-8e68-68a99c3e450d.png)

Thx.

**Comment by chelaruc** [comment]
@Xipotera you need to change manually the color in HTML files. Best, Ciprian
