### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by svplucas** [creativetimofficial/material-dashboard-angular2#45]
I just downloaded the latest version of the theme and tried to npm install the dependencies.
Got the following error:

> npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an
import issue introduced in 2.1.0
npm ERR! Unexpected end of JSON input while parsing near '...^2.79.0","shelljs":"^'

Any enlightment regarding this error?
Thanks in advance.

**Comment by PamilerinId** [comment]
@svplucas  how where you able tosolve this problem

**Comment by svplucas** [comment]
@PamilerinId in my case, i've updated nodeJs/npm and did a npm clean cache before npm install
