### ISSUE TITLE
About Sidebar

### ISSUE THREAD

**Issue by sednaangular** [creativetimofficial/material-dashboard-angular2#47]
How to hide sidebar in login page i.e how can I open login page first without sidebar and then after successful login will redirect on dashboard of template....I tried it but not possible, please give some solution for ur template.....

**Comment by chelaruc** [comment]
@sednaangular what product do you have? We don't have a login page on this product.

**Comment by sednaangular** [comment]
I have the same product, but have created login page in it as per my requirements..
And now I want to hide sidebar on login page in same tmplate

**Comment by chelaruc** [comment]
@sednaangular you need to make 2 layouts for that, one for admin(with sidebar) and one for auth(for example: login, register).

**Comment by sednaangular** [comment]
Sir, does it mean I'll need to create two separate project one will include this template and one with my login, registration form and then will link them with each other.
Please let me know how to do it?

**Comment by chelaruc** [comment]
@sednaangular it will not be separated, but it will have 2 layouts and you need to modify the hole routes from this free version. Best, Ciprian
