### ISSUE TITLE
Style Issue

### ISSUE THREAD

**Issue by MalikRizwanAwan** [creativetimofficial/material-dashboard-angular2#49]
With due respect I want to inform you that this is superb Theme. But the issue i am facing is that when i change in userprofile template everything Ok but when i bind it with component like [(ngModel)]="name" then its style change by default color to green color so please let me know what i have to do. Help would be appreciated

**Comment by chelaruc** [comment]
Hi @MalikRizwanAwan. Can you show me some images and the steps to reproduce the error?

**Comment by MalikRizwanAwan** [comment]
Respected Sir Both screenshot are mentioned here the circle one is actual
one and the other one with green color have different style.I want it just
like actual. It is ok when i use it simply but when i use binding property
of angular its style distrub kindly guide me help would be appreciated

**Comment by MalikRizwanAwan** [comment]
other problem is that drop down is not working here

**Comment by MalikRizwanAwan** [comment]
@chelaruc sir i am waiting for your precious response

**Comment by MalikRizwanAwan** [comment]
![actual](https://user-images.githubusercontent.com/35251864/48111350-f1762100-e272-11e8-808f-0bb7c1048231.png)
![error](https://user-images.githubusercontent.com/35251864/48111352-f20eb780-e272-11e8-9ee8-605b34af771d.png)

these both are the screen shoot value with encircle having indigo color is orignal one but the problem is that when i use angular5 property binding its give the green color by default and cant use steeper in it

**Comment by MalikRizwanAwan** [comment]
@chelaruc  hope you got it

**Comment by chelaruc** [comment]
@MalikRizwanAwan you need to go in src/assets/scss/core/_forms.scss and delete the lines 411 to 425. Best, Ciprian

**Comment by MalikRizwanAwan** [comment]
Thanks alot bunddle of  thanks sir Its work for me .Just superb working by you <3 now i am getting problem for select option @chelaruc . I want a drop down menu but when i use select option its give me following error and style problem which i have  mentioned in screenshoot
![style](https://user-images.githubusercontent.com/35251864/48121860-e2559a00-e297-11e8-85d6-c954940e5ae9.png)

**Comment by MalikRizwanAwan** [comment]
![orignal](https://user-images.githubusercontent.com/35251864/48122001-45473100-e298-11e8-9dfb-1c809a297de1.png)
This is our orignal style. but i am getting above problem. I would be really thankful to you for such kind of favour

**Comment by MalikRizwanAwan** [comment]
In HTML here is not any orignal code for Select or dropdown option

**Comment by MalikRizwanAwan** [comment]
i am using <div class="col-md-4">
                                              <mat-form-field class="example-full-width">
                                                    <select class="form-control " name="Prs_Flg" value="Prs_Flg" ngModel required>
                                                            <option value="1">Permanent Employee</option>
                                                            <option value="2">Temporary Employee</option>
                                                          </select>
                                              </mat-form-field>
                                            </div> @chelaruc

**Comment by MalikRizwanAwan** [comment]
@chelaruc  unfortunatelly i couldn't post the code which i am using  by searching from internet. Now here it is in txt form
[code.txt](https://github.com/creativetimofficial/material-dashboard-angular2/files/2556844/code.txt)

**Comment by MalikRizwanAwan** [comment]
@chelaruc The beautiful and superb theme provided by you have no builtIn dropdown menu or option

**Comment by chelaruc** [comment]
@MalikRizwanAwan  check these links:
[https://material.angular.io/components/input/overview](https://material.angular.io/components/input/overview)
[https://material.angular.io/components/select/overview](https://material.angular.io/components/select/overview)

**Comment by MalikRizwanAwan** [comment]
![option](https://user-images.githubusercontent.com/35251864/48123944-f9e35180-e29c-11e8-8590-81caa7e5e955.png)
@chelaruc  sorry to inform you that i have already used this option and links but out is nill. Here i am again mentioning the screenshoot of my output while i use this one

**Comment by chelaruc** [comment]
@MalikRizwanAwan add this:
```
import {
  MatInputModule,
  MatSelectModule,
} from "@angular/material";
``` 
to your `app.module.ts` file and import them to `imports` from `NgModule`

**Comment by MalikRizwanAwan** [comment]
Its already there i have done this before

**Comment by chelaruc** [comment]
have you used <mat-form-field>?

**Comment by MalikRizwanAwan** [comment]
yes used but no postive response

**Comment by chelaruc** [comment]
and how it looks now? give me the code again

**Comment by MalikRizwanAwan** [comment]
[code.txt](https://github.com/creativetimofficial/material-dashboard-angular2/files/2556924/code.txt)
the above one is code which i am using and below one is its output 
![dropdown](https://user-images.githubusercontent.com/35251864/48124891-4596fa80-e29f-11e8-810e-e2b4b1c09184.png)

**Comment by MalikRizwanAwan** [comment]
If i not use this option everything works fine

**Comment by MalikRizwanAwan** [comment]
Thanks alot its solve my problem

**Comment by MalikRizwanAwan** [comment]
Hi @chelaruc  now i want to inquire that i want to use wizard in form please let me know how can i use it i searched alot by google and apply multiple process but no one is competable with this theme. I am really worried because its my basic requirement. I would be really thankfull to you for this favour

**Comment by MalikRizwanAwan** [comment]
Hi @chelaruc <https://github.com/chelaruc> now i want to inquire that i
want to use wizard in form please let me know how can i use it i searched
alot by google and apply multiple process but no one is competable with
this theme. I am really worried because its my basic requirement. I would
be really thankfull to you for this favour
