### ISSUE TITLE
Port the code in Stackblitz

### ISSUE THREAD

**Issue by RIJUGHOSH** [creativetimofficial/material-dashboard-angular2#52]
Hi,
    I am trying to open the project in Stackblitz for further development, for doing so I went to the github link for the project and changed the URL as given in the [Stackblitz documentation for porting projects from github](https://stackblitz.com/docs#import-from-github), but in stackblitz the Side-nav bar and its components do not appear kindly help me with the same

Thanks,
Riju

**Comment by chelaruc** [comment]
@RIJUGHOSH what errors do you get?
