### ISSUE TITLE
Unable to add/create new component using code for existing components 

### ISSUE THREAD

**Issue by RIJUGHOSH** [creativetimofficial/material-dashboard-angular2#53]
Hi,
    I am attempting to create a new component basic-settings, for this I added the name and icon in the array for sidebar and it displays the icon and text but I need that when I click on this icon it should redirect to the basic settings page where I will only have static html elements like typography page for now, kindly help me how to do it, I already copied the code of typography component and made the relevant changes, but I am having some difficulties adding it to the routing and admin-layout, kindly help me I am stuck with the code

Thanks,
Riju

**Comment by chelaruc** [comment]
@RIJUGHOSH did you managed to do it?
