### ISSUE TITLE
Is angular/material a part of it

### ISSUE THREAD

**Issue by sukheja-varun** [creativetimofficial/material-dashboard-angular2#59]
I can see in the package.json it includes "@angular/material": "7.0.2" but project description states this project is based in Angular7 and Bootstrap4. Shouldn't angular material be stated as well.?

Also including bootstrap and material both won't make the bundle of the project heavy?

**Comment by chelaruc** [comment]
@sukheja-varun Thnak you for using our product. The product has both, Angular Material and Bootstrap.
