### ISSUE TITLE
Error scss mixins

### ISSUE THREAD

**Issue by ghten** [creativetimofficial/material-dashboard-angular2#63]
Hi,

I have this error.
ERROR in ./src/assets/scss/material-dashboard.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/material-dashboard.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
            ^
      Mixin form-validation-state is missing argument $icon.
      in E:\project_angular\fitcontroller\src\assets\scss\core\mixins\_forms.scss (line 159, column 14)

thanks

**Comment by eestein** [comment]
I've got the same error:

```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    @include form-validation-state("valid", $label-color);
            ^
      Mixin form-validation-state is missing argument $icon.
      in /Users/eestein/.../src/assets/styles/core/mixins/_forms.scss (line 159, column 14)
```

**Comment by tbenci** [comment]
11 days and no response from support.

We shouldn't have to deal with issues like this support. It should work out of the box.

**Comment by chelaruc** [comment]
@ghten @eestein @tbenci Check this link for the fix: [https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/316#issuecomment-464326764](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/316#issuecomment-464326764).

**Comment by eestein** [comment]
> @ghten @eestein @tbenci Check this link for the fix: [creativetimofficial/ct-material-dashboard-pro-angular#316 (comment)](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/316#issuecomment-464326764).

Thanks. I had repeated $label-color just to get it working, I'll change it for that one.
