### ISSUE TITLE
[Bug] Charts doesn't work well in tab-pane

### ISSUE THREAD

**Issue by AntonioBusillo** [creativetimofficial/material-dashboard-angular2#71]
### Version
2.2.0
### Reproduction link
https://i.imgur.com/GDgy3up.gifv
### Operating System
WSL
### Device
PC
### Browser & Version
Chrome
### Steps to reproduce
Add a chart (chartist.js or devextreme one) in a tab-pane 
### What is expected?
I want to put a chart in a tab-pane, and have it in full width of the card but every chart I try (chartist, devextreme etc) doesn't work.
### What is actually happening?
Every chart has problem or doesn't resize. 

---
### Additional comments
I uploaded a GIF because I can't give access to our environment.

**Comment by AntonioBusillo** [comment]
I tried with a fresh new dashboard, adding a Chartist.js component into a tab-panel in the Panel page. I have a similar problem. 

https://i.imgur.com/6MhMNWa.gifv

You can try, I added the Rounded Coloured Line Char: colouredRoundedLineChart

**Comment by AntonioBusillo** [comment]
Tried also with Edge and Firefox

**Comment by chelaruc** [comment]
Hi, @AntonioBusillo. I don't know why it doesn't work correctly, but we found a solution for this. I'll attach an archive with the panels files here.
[panels.zip](https://github.com/creativetimofficial/material-dashboard-angular2/files/3371772/panels.zip)
