### ISSUE TITLE
navbar-toggling not working

### ISSUE THREAD

**Issue by BLasan** [creativetimofficial/material-dashboard-angular2#74]

**Comment by BLasan** [comment]
navbar toggling not working properly. No dropdowns when move on to the mobile view

**Comment by chelaruc** [comment]
Hello there, @BLasan 

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Ciprian
Developer @ Creative-Tim.com (https://creative-tim.com/)
