### ISSUE TITLE
[Bug] Edge and Internet Explorer Not Supported

### ISSUE THREAD

**Issue by damienbdg** [creativetimofficial/material-dashboard-angular2#76]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/material-dashboard-angular2/#/dashboard
### Operating System
Windows 10
### Device
PC
### Browser & Version
Edge, IE 11
### Steps to reproduce
1. ng serve
2. Try to open in Internet Explorer
### What is expected?
App will run
### What is actually happening?
App does not run. Many console errors about "ERROR ReferenceError: '$' is undefined"

---
### Solution
Unknown

**Comment by chelaruc** [comment]
Hi, @damienbdg. Thank you for using our product. Unfortunately, we don't support IE anymore. 
The solution to your problem is here: https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/339
