### ISSUE TITLE
[Feature Request] Can we have an example to add multi-select drop list to right-side FixedPlugin control please?

### ISSUE THREAD

**Issue by adipple** [creativetimofficial/material-dashboard-angular2#78]
### What is your enhancement?
I'm wanting to use the FixedPlugin as a query filter on a page, where I have various controls (check box, drop list, etc).  My check box and drop list work as expected, but the multi-select drop list from the ExtendedForm closes the FixedPlugin when selected.

Can this example be added please, as it would be a very powerful UI pattern. 

I have asked for help on StackOverflow, but not looking like it's attracting help:
https://stackoverflow.com/questions/59077715/how-to-make-creative-tim-angular-material-pro-show-multi-select-drop-list-on-fil

**Comment by chelaruc** [comment]
Hi, @adipple! Thank you for using our product. Please open the issue to the right repository: [https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues). All the best, Ciprian
