### ISSUE TITLE
[Feature Request] How can I add colour regions to the JVectorMap?

### ISSUE THREAD

**Issue by adipple** [creativetimofficial/material-dashboard-angular2#79]
### What is your enhancement?
I'm wanting to create coloured regions on the JVectorMap but when I add the region series per all examples found on the web, the map just will not render the colours.

The examples use the JVectorMap "world-mill-en" map, but that file does not seem to work for me in the project.  I get what looks like a JQuery error about missing elements so I can't verify if the colouring problem is because of the vector file versions.  I don't know if there is some overriding CSS or events?
 
Can an example of adding coloured regions be added please. 

I have asked for help on StackOverflow, but not looking like it's attracting help:
https://stackoverflow.com/questions/59080576/how-to-have-creative-tim-angular-material-pro-render-regions-on-jvectormap

It would be very useful to see this as the configuration of JVectorMap in the angular project is different to how a different StackOverflow example explains to install/configure.

**Comment by chelaruc** [comment]
Hi, @adipple! Thank you for using our product. Please open the issue to the right repository: [https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues). All the best, Ciprian
