### ISSUE TITLE
"@agm/core" has an incompatible peer dependency to "@angular/core" (requires "^5.0.0 || ^6.0.0" (extended), would install "8.2.14").

### ISSUE THREAD

**Issue by rsRamgharia** [creativetimofficial/material-dashboard-angular2#82]
Please update your packages. maybe your customers facing the same issue as me. I download the project yesterday and got too many errors.

![image](https://user-images.githubusercontent.com/50511441/71511815-a9242300-28b9-11ea-8cbb-fafd60b882e6.png)

**Comment by rsRamgharia** [comment]
New error

![image](https://user-images.githubusercontent.com/50511441/71512017-6c0c6080-28ba-11ea-8c66-6c60a6126ed3.png)

**Comment by chelaruc** [comment]
@rsRamgharia check this example:
```
 @ViewChild(ChildDirective, {static: false}) Component
```
you need to add static:false
