### ISSUE TITLE
[Bug] dropdown not working

### ISSUE THREAD

**Issue by totalpanic** [creativetimofficial/material-dashboard-angular2#84]
### Version
2.3.0
### Reproduction link
https://demos.creative-tim.com/material-dashboard-angular2/#/dashboard
### Operating System
Windows 10
### Device
Workstation
### Browser & Version
Edge and IE11
### Steps to reproduce
1: start project
2: browse to dashboard
3: click on "Notifications" icon in top bar
### What is expected?
a dropdown with notifications appears
### What is actually happening?
console error and nothing on the UI
errors are as follows:

SCRIPT1002: Syntax error
ERROR ReferenceError: '$' is undefined

---

**Comment by chelaruc** [comment]
Hi, @totalpanic. Thank you for using our product. Check this issue from the PRO version: https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/339. There you have the fix for this problem. We will update this product soon with the correct code.
